SamwelWeb/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Samwel.DataAccess.Repository;
using Samwel.DataAccess.Repository.IRepository;
using Samwel.Models;
using Samwel.Utility;

namespace SamwelWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _companyRepository;
        public CompanyController(IUnitOfWork repository)
        {
            _companyRepository = repository;
        }
        public IActionResult Index()
        {
            var Categories =
                _companyRepository.Company.GetAll(null);
            return View(Categories);
        }

        public IActionResult Create()
        {
            return View();
        }
		[HttpPost]
		public IActionResult Create(Company company)
		{
		
			if (!ModelState.IsValid)
				return View();
			_companyRepository.Company.Add(company);
			TempData["Hello"] = $"We Create {company.Name} company";
			return RedirectToAction("Index");
		}

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var Company =
                _companyRepository
                .Company.Get(u => u.Id == Id);

            if (Company == null)
                return NotFound();
            return View(Company);
        }
        [HttpPost]
        public IActionResult Edit(Company company)
        {
          

            if (!ModelState.IsValid)
                return View();
            _companyRepository.Company.Update(company);
            _companyRepository.Save();
            TempData["Hello"] = $"We Edit {company.Name} company";

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            var Compay = _companyRepository.
                Company.Get(c => c.Id == Id);

            if (Compay == null)
                return NotFound();
            return View(Compay);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? Id)
        {
            var Compay = _companyRepository.
              Company.Get(c => c.Id == Id);

            if (Compay == null)
                return NotFound();
            _companyRepository.Company.Remove(Compay);

            TempData["Hello"] = $"We Delete {Compay.Name} Compay";

            return RedirectToAction("Index");
        }
    }
}

SamwelWeb/Areas/Admin/Controllers/OrderController.cs
using System.Diagnostics;
using System.Security.Claims;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Samwel.DataAccess.Repository;
using Samwel.DataAccess.Repository.IRepository;
using Samwel.Models;
using Samwel.Models.ViewModels;
using Samwel.Utility;
using Stripe;
using Stripe.Checkout;
using Stripe.Issuing;

namespace SamwelWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]	
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _orderRepository;
		[BindProperty]
		public OrderVM order { get; set; }	

        public OrderController(IUnitOfWork _orderRepository)
		{
			this._orderRepository = _orderRepository;
		}
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Details(int id)
		{
			OrderVM orderVM = new OrderVM()
			{
				OrderHeader = _orderRepository.OrderHeader.Get(x => x.Id == id , include: "AppUser")!,
				Details = _orderRepository.OrderDetails.GetAll(x => x.OrderHeaderId == id , include:"Product")	
			};
			return View(orderVM);
		}
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        [HttpPost]
        public IActionResult StartProcessing ()
		{
			_orderRepository.OrderHeader.UpdateStatus(order.OrderHeader.Id, SD.StatusInProcess);
			_orderRepository.Save();
            TempData["Hello"] = $"We update Ordere ";

            return RedirectToAction(nameof(Details), new { id = order.OrderHeader.Id });

        }
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        [HttpPost]
        public IActionResult ShipOrder()
        {
			var orderheader = 
				_orderRepository.OrderHeader.Get(c=>c.Id == order.OrderHeader.Id);
			orderheader!.Carrier = order.OrderHeader.Carrier;
            orderheader!.TrackingNumber = order.OrderHeader.TrackingNumber;
            orderheader!.ShippingDate = DateTime.Now;
			orderheader!.OrderStatus = SD.StatusShipped; 
			if (orderheader.PaymentStatus == SD.PaymentStatusDelayedPayment)
			{
				orderheader.PaymentDueDate = DateTime.Now.AddDays(30);
			}

            _orderRepository.OrderHeader.Update(orderheader);
            _orderRepository.Save();
            TempData["Hello"] = $"We Shipped Ordere ";

            return RedirectToAction(nameof(Details), new { id = order.OrderHeader.Id });

        }
        public IActionResult CancelOrder()
        {
            var orderheader =
                _orderRepository.OrderHeader.Get(c => c.Id == order.OrderHeader.Id);
         
			if (orderheader!.PaymentStatus == SD.PaymentStatusApproved)
			{
				var options = new RefundCreateOptions()
				{
					Reason = RefundReasons.RequestedByCustomer ,
					PaymentIntent = orderheader.PaymentIntendId
                };
				var service = new RefundService();

				Refund refund = service.Create(options);
				_orderRepository.OrderHeader.UpdateStatus
					(orderheader.Id, SD.StatusCancelled , SD.StatusRefunded) ;

			}
			else
			{
                _orderRepository.OrderHeader.UpdateStatus
                (orderheader.Id, SD.StatusCancelled);
            }

            _orderRepository.Save();
            TempData["Hello"] = $"We  Ordere Cancelled ";

            return RedirectToAction(nameof(Details), new { id = order.OrderHeader.Id });
        }

		[ActionName("Details")]
		[HttpPost]
		public IActionResult Details_PAY_NOW ()
		{
            order.OrderHeader = _orderRepository.OrderHeader.Get(x => x.Id == order.OrderHeader.Id, include: "AppUser")!;
            order.Details = _orderRepository.OrderDetails.GetAll(x => x.OrderHeaderId == order.OrderHeader.Id, include: "Product");
            var Domain = Request.Scheme+"://"+Request.Host.Value;
            var options = new SessionCreateOptions
            {
                SuccessUrl = Domain + $"/admin/order/PaymentConfirmation?id={order.OrderHeader.Id}",
                CancelUrl = Domain + $"/admin/order/details?id={order.OrderHeader.Id}" ,
                Mode = "payment",
                LineItems = new()
            };
            foreach (var item in order.Details)
            {
                var sessionlineItem = new SessionLineItemOptions
                {
                    PriceData = new()
                    {
                        UnitAmount = (long)item.Price * 100,
                        Currency = "usd",
                        ProductData = new()
                        {
                            Name = item.Product.Title
                        }
                    }
                    ,
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionlineItem);
            }

            var service = new SessionService();
            Session session = service.Create(options);
            _orderRepository
                .OrderHeader.UpdateSripePaymentID(order.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _orderRepository.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);

        }
        public IActionResult PaymentConfirmation(int id)
        {
            var OrderHeader = _orderRepository.OrderHeader.Get(x => x.Id == id)!;
            if (OrderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(OrderHeader.SessionId);
                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _orderRepository.OrderHeader
                        .UpdateSripePaymentID(OrderHeader.Id, session.Id, session.PaymentIntentId);
                    _orderRepository.
                        OrderHeader.UpdateStatus(id,OrderHeader.State, SD.PaymentStatusApproved);
                    _orderRepository.Save();
                }
                
            }

     
            return View(id);
        }
        [Authorize(Roles = SD.Role_Admin +","+SD.Role_Employee)]
		[HttpPost]
        public IActionResult UpdateOrderDetails()
        {
			var orderheader = _orderRepository.OrderHeader.
				Get(x=>x.Id == order.OrderHeader.Id);
			orderheader!.Name = order.OrderHeader.Name;
            orderheader.PhoneNumber = order.OrderHeader.PhoneNumber;
            orderheader.City = order.OrderHeader.City;
            orderheader.State = order.OrderHeader.State;
            orderheader.PostalCode = order.OrderHeader.PostalCode!;
            orderheader.StreetAddress = order.OrderHeader.StreetAddress;
			if (!string.IsNullOrEmpty(order.OrderHeader.Carrier))
                orderheader.Carrier = order.OrderHeader.Carrier;
            if (!string.IsNullOrEmpty(order.OrderHeader.TrackingNumber))
                orderheader.TrackingNumber = order.OrderHeader.TrackingNumber;
			_orderRepository.OrderHeader.Update(orderheader);
            TempData["Hello"] = $"We update Ordere ";

            _orderRepository.Save();
			return RedirectToAction(nameof(Details), new { id = orderheader.Id });
        }
        #region API CALLS
        public IActionResult GetAll(string status)
		{
			 IEnumerable<OrderHeader> OrderHeader;
            if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee))
			{
                OrderHeader = _orderRepository.OrderHeader.GetAll(null, "AppUser");
            }
			else
			{
                var Claim = (ClaimsIdentity)User.Identity!;
                var userId = Claim.FindFirst(ClaimTypes.NameIdentifier)!.Value;
				OrderHeader = _orderRepository
					.OrderHeader.GetAll(u => u.AppUserId == userId, include: "AppUser");
            }

            switch (status)
			{
				case "pending":
					OrderHeader = OrderHeader.Where(x => x.PaymentStatus == SD.PaymentStatusDelayedPayment);
					break;
				case "approved":
					OrderHeader = OrderHeader.Where(x => x.OrderStatus == SD.StatusApproved);
					break;
				case "inprocess":
					OrderHeader = OrderHeader.Where(x => x.OrderStatus == SD.StatusInProcess);
					break;
				case "completed":
					OrderHeader = OrderHeader.Where(x => x.OrderStatus == SD.StatusShipped);
					break;
				default:
					break;
			}
			return
				Json(new { data = OrderHeader });
		}
		#endregion
	}
}

SamwelWeb/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Samwel.DataAccess.Data;
using Samwel.DataAccess.Repository;
using Samwel.DataAccess.Repository.IRepository;
using Samwel.Models;
using Samwel.Models.ViewModels;
using Samwel.Utility;
using System.Collections.Immutable;
using System.Linq.Expressions;
namespace SamwelWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
   [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly AppDbContext _UserRepository;
        public UserController(AppDbContext repository)
        {
            _UserRepository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }



        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var users = _UserRepository.AppUsers.Include(u=>u.Company).ToList(); 
            var userroles = _UserRepository.UserRoles.ToList();
            var roles = _UserRepository.Roles.ToList();
            foreach (var user in users) 
            {
                string roleId; 
                var haverole = userroles.FirstOrDefault(x => x.UserId == user.Id);
                if (haverole != null)
                {
                    roleId = haverole.RoleId;
                    user.RoleName = roles.FirstOrDefault(c => c.Id == roleId).Name;
                }

                if (user.Company == null)
                {
                    user.Company = new Company
                    {
                        Name = "Not Comapny "
                    };
                }

            }
            return
                Json(new { data = users });
        }

        [HttpPost]
        public IActionResult LockUnLock(string ? id)
        {
   
            var user = _UserRepository.AppUsers.
                FirstOrDefault(x => x.Id == id);
            if (user == null)
            {
                return Json(new { success = false, message = "Error while Lock or UnLock " }); 
            }
            if (user
                .LockoutEnd!=null && user.LockoutEnd>DateTime.Now)
            {
                user
                .LockoutEnd = DateTime.Now; 
            }
            else
            {
                user
                .LockoutEnd = DateTime.Now.AddYears(1000); 
            }
            _UserRepository.SaveChanges (); 
            return
                Json(new { success = true, message = "Ok .. " });

        }
        #endregion



        public IActionResult Manageuser (string ? id)
        {
            if (id == null)
                return NotFound(); 
           var user =  _UserRepository.AppUsers.First(x => x.Id == id); 
           var roles = _UserRepository.Roles.ToList();
           var roleid = _UserRepository.UserRoles.FirstOrDefault(x=>x.UserId == id).RoleId;

            var data = new ManageuserVM
            {
                Name = user.Name,
                RolesList = roles.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id
                })
                ,
                CompanyList = _UserRepository
                .Companies.Select(c => new SelectListItem
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                })
                ,
                Role = _UserRepository.Roles.First(x => x.Id == roleid).Name 
            };
            return View(data); 
        }
        [HttpPost]
        public IActionResult Manageuser(ManageuserVM manageuser)
        {
            var user = _UserRepository.AppUsers.First(x => x.Id == manageuser.Id);
            user.Name = manageuser.Name;
            var userrole =
                _UserRepository.UserRoles.First(x => x.UserId == manageuser.Id);
             _UserRepository.Remove(userrole);
            _UserRepository.SaveChanges();
            _UserRepository.UserRoles.Add
                (new Microsoft.AspNetCore.Identity.IdentityUserRole<string>()
                {
                    UserId = manageuser.Id,
                    RoleId = manageuser.Role
                }); 
            if  (manageuser.Company != 0) 
            {
                user.CompanyId = manageuser.Company; 
            }
            else
            {
                user.CompanyId = null;
            }
   
            _UserRepository.SaveChanges(); 
            return RedirectToAction("Index");
        }
    }
}

SamwelWeb/ViewComponent/ShoppingCartViewComponent.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Samwel.DataAccess.Repository;
using Samwel.DataAccess.Repository.IRepository;
using Samwel.Utility;

namespace SamwelWeb.ViewComponent
{
    public class ShoppingCartViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly IUnitOfWork _Repository;
        public ShoppingCartViewComponent(IUnitOfWork repository)
        {
            _Repository = repository;
           
        }
        public async Task <IViewComponentResult> InvokeAsync()
        {
            var Claim = (ClaimsIdentity)User.Identity!;
            var Check = Claim.FindFirst(ClaimTypes.NameIdentifier);
            if (Check != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart)== null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _Repository.
                   ShoppingCart.GetAll(x => x.AppUserId == Check.Value)!.Count());
  
                }
             
                return View(HttpContext.Session.GetInt32(SD.SessionCart)); 
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }

        }
    }
}

SamwelWeb/Views/Shared/_Layout.cshtml
@using Samwel.Utility;
@using Microsoft.AspNetCore.Http 
@inject IHttpContextAccessor HttpContextAccessor 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SamwelWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" href="~/SamwelWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img  src="~/Images/book.png" style="width:30px"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
     

                       @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Managment
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity"  asp-page="/Account/Register">Create User </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Mange Users </a>
                                    </li>
                                </ul>
                            </li>
                        }     
                    
                              <li class="nav-item">
                                <a class="nav-link " asp-area="Customer" asp-controller="ShoppingCart"
                               asp-action="Index">
                               @await Component.InvokeAsync("ShoppingCart")
                           </a>
                            </li>
                        
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary ">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> By  Samwel Marzouk
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>

    <script src="https://cdn.tiny.cloud/1/tfb9kebjcndmhjl5resg5u7e2ofw0mfnek43bn6wrrqmbw8g/tinymce/6/tinymce.min.js" referrerpolicy="origin">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    </script>
   
 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SamwelWeb/Views/Shared/_Notification.cshtml
@if (TempData["Hello"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>

	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["Hello"]')
	</script>

}